;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        electric-pair-delete-pair
        end-of-visual-line
        evilnc-comment-or-uncomment-lines
        indent-for-tab-command
        ivy-alt-done
        ivy-next-line
        keyboard-escape-quit
        kill-region
        markdown-electric-backquote
        markdown-enter-key
        markdown-outdent-or-delete
        org-self-insert-command
        puppet-align-block
        puppet-apply
        puppet-interpolate
        ruby-electric-bar
        ruby-electric-closing-char
        ruby-electric-curlies
        ruby-electric-delete-backward-char
        ruby-electric-hash
        ruby-electric-matching-char
        ruby-electric-space/return
        sh-assignment
        suspend-frame
        web-mode-element-insert
        xterm-paste
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-backward-delete-char
        overwrite-mode
        save-buffers-kill-terminal
        ))
