;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        ruby-electric-closing-char
        ruby-electric-delete-backward-char
        ruby-electric-matching-char
        ruby-electric-space/return
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ))
