;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        electric-pair-delete-pair
        end-of-visual-line
        ess-smart-comma
        ess-yank
        evilnc-comment-or-uncomment-lines
        indent-for-tab-command
        ivy-alt-done
        ivy-next-line
        keyboard-escape-quit
        kill-region
        markdown-electric-backquote
        markdown-end-of-line
        markdown-enter-key
        markdown-outdent-or-delete
        move-line-down
        org-end-of-line
        org-metaright
        org-self-insert-command
        puppet-align-block
        puppet-apply
        puppet-interpolate
        ruby-electric-bar
        ruby-electric-closing-char
        ruby-electric-curlies
        ruby-electric-delete-backward-char
        ruby-electric-hash
        ruby-electric-matching-char
        ruby-electric-space/return
        sh-assignment
        skeleton-pair-insert-maybe
        suspend-frame
        tabnine-accept-completion
        tabnine-clear-overlay
        transpose-character-left
        web-mode-comment-or-uncomment
        web-mode-element-close
        web-mode-element-insert
        xterm-paste
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        delete-window
        handle-switch-frame
        ivy-backward-delete-char
        ivy-previous-line
        overwrite-mode
        save-buffers-kill-terminal
        swiper
        ))
